# Generated by Django 3.1.14 on 2023-11-16 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20231116_0709'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.cart')),
            ],
        ),
    ]
